[package]
name = "rebind_example"
version = "0.1.0"
authors = ["George Burton <burtonageo@gmail.com>"]

[dependencies]
piston = "~0.10.0"
piston2d-graphics = "~0.4"
piston2d-opengl_graphics = "~0.6"
pistoncore-glutin_window = "~0.12"
piston-viewport = "~0.1"
conrod = "~0.14"

[dependencies.rebind]
path = ".."
